name: CI build ip mail sender

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Build the back
    - name: Build email sender
      run: |
        echo Run build mail sender
        cd src/main
        export GOOS=linux
        export GOARCH=arm
        go build -o ip_getter_server ip_getter.go
        cd ../../
        mkdir artifacts
        echo Copy sender app artifact in artifacts/
        mv src/main/ip_getter_server artifacts

  # Upload artifact
    - uses: actions/upload-artifact@v1
      with:
        name: Artifacts email sender app
        path: artifacts
